// Display mappings from https://wiki.warframe.com/w/World_State
// LICENSE: WARFRAME Wiki contributors - CC BY-NC-SA 3.0
export const worldStateMappings = {
	"relicTier": {
		"VoidT1": "Lith",
		"VoidT2": "Meso",
		"VoidT3": "Neo",
		"VoidT4": "Axi",
		"VoidT5": "Requiem",
		"VoidT6": "Omnia"
	},
	"alert": {
		"LotusGift": "Gift of the Lotus",
		"TacAlertWaterFight": "Dog Days",
		"WolfAlert": "Wolf Hunt"
	},
	"archimedeaType": {
		"CT_LAB": "Deep Archimedea",
		"CT_HEX": "Temporal Archimedea"
	},
	"temporalDeviation": {
		"ChemicalNoise": "Noise Suppression",
		"ContaminationZone": "Hold Your Breath",
		"DisruptiveSounds": "Vamp Rock",
		"DoubleTroubleLegacyte": "Mitosis",
		"EscalateImmediately": "Cache Crash",
		"ExplosiveEnergy": "Miasmite Mash",
		"FortifiedFoes": "Sealed Armor",
		"GestatingTumors": "Sporogenesis",
		"HighScalingLegacyte": "Growth Hormones",
		"HostileSecurity": "Disruptive Sounds",
		"MutatedEnemies": "Parallel Evolution",
		"TankReinforcements": "Reinforcements",
		"TankStrongArmor": "Thermian Plating",
		"TankSuperToxic": "Toxic Tank",
		"TechrotConjunction": "Pile-On"
	},
	"deepDeviation": {
		"FortifiedFoes": "Sealed Armor",
		"AlchemicalShields": "Alchemical Invulnerability",
		"DoubleTrouble": "Double Demolishers",
		"DuoAssassination": "The Fragmented Two",
		"EnemyLink": "Damage Link",
		"EnvironmentalSystem": "Hazardous Areas",
		"EximusGrenadiers": "Eximus Amphors",
		"FragileNodes": "Unified Purpose",
		"GrowingIncursion": "Fissure Cascade",
		"HarshWords": "Barbed Glyphs",
		"HostileSecurity": "Eroding Senses",
		"HungryPillars": "Radioactive Breakdown",
		"InfiniteTide": "Relentless Tide",
		"LostInTranslation": "Glyph Inflation",
		"MisguidedInstructions": "Glyph Trap",
		"NecramechActivation": "Necramech Influx",
		"NecramechLockout": "Hostile Support",
		"Reinforcements": "Coordinated Front",
		"SameTeam": "Angelic Cohort",
		"StickyFingers": "Engorged Gruzzlings",
		"UnpoweredCapsules": "Parasitic Towers",
		"VolatileGrenades": "Hazardous Goods"
	},
	"archimedeaRisk": {
		"AcceleratedEnemies": "Bold Venture",
		"AntiMaterialWeapons": "Commanding Culverins",
		"ArcadeAutomata": "Arcade Automata",
		"ArtilleryBeacons": "Artillery Beacons",
		"BalloonFest": "Balloonfest",
		"CompetitionSpillover": "Competitive Streak",
		"Deflectors": "Fortified Foes",
		"DrainingResiduals": "Devil's Bargain",
		"EfervonFog": "Dense Fog",
		"EmpoweredEnemies": "Proportional Resistance",
		"EnemyElementalEnhancement": "Elemental Potency",
		"ExplosiveCrawlers": "Explosive Potential",
		"ExplosiveSummer": "Excessive Explosives",
		"Scaldra": "Scaldra Speed Run",
		"Techrot": "Techrot Speed Run",
		"FallFog": "Foggy Fall",
		"HeavyWarfare": "Heavy Warfare",
		"HostileOvergrowth": "It's Alive",
		"InfectedTechrot": "Corrupted Flesh",
		"JadeSpring": "Jade Spirits",
		"MagneticHounds": "Alluring Arcocanids",
		"MeleeOnlyEnemies": "Close Quarters",
		"MiasmiteHive": "Miasmite Swarm",
		"MurmurIncursion": "Beyond The Wall",
		"PointBlank": "Myopic Munitions",
		"Quicksand": "Entanglement",
		"RangedOnlyEnemies": "Ranged Engagements",
		"RegeneratingEnemies": "Hostile Regeneration",
		"RestrictedConsumables": "Delayed Supply",
		"RestrictedRespawns": "Finality",
		"SentientAdaptation": "Adaptive Aberrations",
		"ShieldedFoes": "Bolstered Belligerents",
		"Vanquisher": "Eximus Reinforcements",
		"VoidAberration": "Vampyric Liminus",
		"Voidburst": "Postmortal Surges",
		"WinterFrost": "Thick Ice"
	},
	"archimedeaModifier": {
		"AbilityLockout": "Powerless",
		"AntiGuard": "Dropped Guard",
		"Armorless": "Fractured Armor",
		"ComboCountChance": "Dull Blades",
		"Conductive": "Conductive",
		"ContactDamage": "Secondary Wounds",
		"DamageMomentum": "Terminal Velocity",
		"DecayingFlesh": "Permanent Injury",
		"EnergyStarved": "Constricted",
		"Exhaustion": "Energy Exhaustion",
		"ExposureCurse": "Exposure Curse",
		"Framecurse": "Framecurse Syndrome",
		"Gearless": "Gear Embargo",
		"Knifestep": "Knifestep Syndrome",
		"MaxAmmo": "Undersupplied",
		"OperatorLockout": "Transference Distortion",
		"OverSensitive": "Hypersensitive",
		"Sanguine": "Sanguine Syndrome",
		"ScarcityCurse": "Ammo Scarcity",
		"ShieldDelay": "Lethargic Shields",
		"Starvation": "Ammo Deficit",
		"TimeDilation": "Abbreviated Abilities",
		"Vampyri": "Vampyric Syndrome",
		"VitalEnergy": "Concussive Drain",
		"VoidEnergyOverload": "Ability Overload",
		"Withering": "Untreatable"
	},
	"descendiaObjective": {
		"DT_BREAK_TARGETS": "Destroy Hologlobes",
		"DT_LOOT_CREATURES": "Gruzzling Plunder",
		"DT_ALCHEMY": "Alchemy",
		"DT_INTERCEPTION": "Mobile Interception",
		"DT_INFESTED_SALVAGE": "Infested Salvage",
		"DT_SABOTAGE_HIVE": "Hive",
		"DT_PROTOFRAME": "Protoframe room",
		"DT_CAPTURE": "Capture",
		"DT_MIMICS": "Plunder Roulette",
		"DT_COLLECTION": "Void Flood",
		"DT_BOSS": "Assassination",
		"DT_EXTERMINATE": "Exterminate",
		"DT_NETRACELLS": "Targeted Elimination",
		"DT_SABOTAGE_DEFENSE": "Defense",
		"DT_DEFENSE": "Protoframe Defense",
		"DT_EXCAVATION": "Excavation",
		"DT_PRESURE_GAUGE": "Volatile"
	},
	"descendiaChallenge": {
		"NC_SlipAndSlide": "Frictionless without enemies",
		"BasicLootCreatures": "Gruzzling Plunder",
		"MineField": "Minefield",
		"SlipAndSlide": "Frictionless",
		"Escapist": "Sneaky Retreats",
		"VoidAberration": "Vampyric Liminus",
		"Wisp": "Marie",
		"FireAndIce": "Eximus Cabal: Fire & Ice",
		"BasicMimics": "Plunder Roulette",
		"NC_MineField": "Minefield without enemies",
		"Octopede": "The Fragmented",
		"PoisonGas": "Chemical Warfare",
		"GlassMaker": "Glassmaker Cephalites",
		"Harrow": "Lyon",
		"Darkness": "Sol Banished",
		"SpicyKnife": "Bomb Defusal",
		"JumpSmash": "Head Stompers",
		"Manics": "Manic Mania",
		"CollectionBasic": "Void Flood",
		"GiantRealm": "Gigantism",
		"Devil": "Roathe"
	},
	"descendiaLevel": {
		"/Lotus/Levels/DevilTower/ProtoframeRoomWisp.level": "Marie's Sanctuary",
		"/Lotus/Levels/DevilTower/ProtoframeRoomHarrow.level": "Lyon's Sanctuary",
		"/Lotus/Levels/DevilTower/BossArenaUriel.level": "Roathe's Throne Room"
	},
	"descendiaEnemies": {
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHCorpusExterminateMixed": "Corpus",
		"/Lotus/Types/Game/EnemySpecs/VaniaExterminateTechrotSpec": "Techrot",
		"/Lotus/Types/Game/EnemySpecs/Duviri/Arena/DuviriExterminateHardmodeA": "Duviri",
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHInfestedMicroplanet": "Grey Strain",
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHForestGrineerFairy": "Frontier Grineer",
		"/Lotus/Types/Game/EnemySpecs/EntratiLab/EntratiSwarmSpec": "The Murmur",
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHCorpusZarimanExterminateSpec": "Juno Corpus",
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHGrineerExterminateFire": "Grineer",
		"/Lotus/Types/Game/EnemySpecs/Duviri/Arena/DuviriSurvivalSpecA": "Corrupted, Duviri, and Thrax enemies",
		"/Lotus/Types/Game/EnemySpecs/VaniaExterminateScaldraNoBalloonSpec": "Scaldra without Scaldra Harbinger",
		"/Lotus/Types/Game/EnemySpecs/Narmer/PNWNarmerForestGrineerExterminate": "All Factions",
		"/Lotus/Types/Game/EnemySpecs/Tau/CoHManicSpec": "All Manics",
		"/Lotus/Types/Game/EnemySpecs/Tau/Tau12MinWarDaxSpec": "Anarchs"
	},
	"descendiaPenance": {
		"/Lotus/Types/Scripts/Tau/CoH/Complications/CoHSlipAndSlideAura": "Frictionless",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/CoHMineFieldAura": "Minefield",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/CoHEscapistAura": "Sneaky Retreats",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/DarknessAura": "Sol Banished/Vampyric Liminus (lights off)",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/CoHVoidAberrationAura": "Vampyric Liminus",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/FireAndIceEnhancementAura": "Eximus Cabal: Fire & Ice",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/PoisonGasAura": "Chemical Warfare",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/GlassMakerAura": "Glassmaker Cephalites",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/SpicyKnifeAura": "Bomb Defusal",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/JumpSmashAura": "Head Stompers",
		"/Lotus/Types/Scripts/Tau/CoH/Complications/GiantRealmAura": "Gigantism"
	},
	"booster": {
		"GAMEPLAY_KILL_XP_AMOUNT": "Affinity Booster",
		"GAMEPLAY_MONEY_REWARD_AMOUNT": "Credit Booster",
		"GAMEPLAY_PICKUP_AMOUNT": "Resource Booster"
	},
	"construction": {
		"CorpusRazorbackProject": "Razorback Armada",
		"Fomorian": "Fomorian Sabotage",
		"HeatFissure": "Thermia Fractures",
		"GhoulEmergence": "Ghoul Purge"
	},
	"marketCategory": {
		"NEW_PLAYER": "For New Tenno",
		"NEW": "NEW",
		"POPULAR": "POPULAR",
		"TENNOGEN": "TENNOGEN",
		"SEASONAL": "SEASONAL",
		"HEIRLOOM": "HEIRLOOM",
		"SALE": "SALE",
		"WISH_LIST": "WISHLIST",
		"PREMIUM_BUNDLES": "PREMIUM BUNDLES",
		"QUICK_BUY": "Quick Buy"
	},
	"calendarEvent": {
		"CET_CHALLENGE": "To Do",
		"CET_REWARD": "Prizes",
		"CET_UPGRADE": "Hex Override"
	},
	"calendarChallenge": {
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillTechrotEnemiesWithAbilitiesEasy": "Null And Void\nx 100 Techrot",
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillTechrotEnemiesWithMeleeEasy": "Electronic Waste Disposal\nx 100 Techrot",
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillScaldraEnemiesMedium": "Punish Scaldra\nx 350 Scaldra",
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillScaldraEnemiesWithMeleeMedium": "Make It Personal\nx 150 Scaldra",
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillEnemiesWithMeleeHard": "By the Blade\nx 500 enemies",
		"/Lotus/Types/Challenges/Calendar1999/CalendarKillTankHard": "Tankless Work\nx 1 H-09 Efervon Tank"
	},
	"calendarReward": {
		"/Lotus/StoreItems/Types/BoosterPacks/CalendarArtifactPack": "1 x Arcane Enhancement",
		"/Lotus/StoreItems/Types/BoosterPacks/CalendarMajorArtifactPack": "2 x Arcane Enhancements",
		"/Lotus/StoreItems/Upgrades/Mods/FusionBundles/CircuitSilverSteelPathFusionBundle": "6000 x Endo",
		"/Lotus/Types/StoreItems/Packages/Calendar/CalendarKuvaBundleLarge": "6000 x Kuva",
		"/Lotus/Types/StoreItems/Boosters/ModDropChanceBooster3DayStoreItem": "3-Day Mod Drop Chance Booster",
		"/Lotus/StoreItems/Types/Recipes/Components/WeaponUtilityUnlockerBlueprint": "1 x Exilus Weapon Adapter Blueprint",
		"/Lotus/StoreItems/Types/Recipes/Components/OrokinCatalystBlueprint": "1 x Orokin Catalyst Blueprint",
		"/Lotus/StoreItems/Types/BoosterPacks/CalendarRivenPack": "1 x Riven Mod",
		"/Lotus/StoreItems/Types/Gameplay/NarmerSorties/ArchonCrystalOrange": "1 x Topaz Archon Shard"
	},
	"calendarOverride": {
		"/Lotus/Upgrades/Calendar/HealingEffects": "Emergency Medicine",
		"/Lotus/Upgrades/Calendar/RadiationProcOnTakeDamage": "Psionic Feedback",
		"/Lotus/Upgrades/Calendar/AbilityStrength": "Power Gains",
		"/Lotus/Upgrades/Calendar/CompanionsRadiationChance": "Friendly Fallout",
		"/Lotus/Upgrades/Calendar/ElectricDamagePerDistance": "Static Buildup",
		"/Lotus/Upgrades/Calendar/MagnitizeWithinRangeEveryXCasts": "Magnetic Menace",
		"/Lotus/Upgrades/Calendar/Armor": "Thick Skin",
		"/Lotus/Upgrades/Calendar/PunchToPrimary": "Punchcard",
		"/Lotus/Upgrades/Calendar/MeleeCritChance": "Practiced Precision"
	},
	"calendarSeason": {
		"CST_WINTER": "Winter",
		"CST_SPRING": "Spring",
		"CST_SUMMER": "Summer",
		"CST_AUTUMN": "Autumn"
	},
	"archonBoss": {
		"SORTIE_BOSS_AMAR": "Archon Amar",
		"SORTIE_BOSS_BOREAL": "Archon Boreal",
		"SORTIE_BOSS_NIRA": "Archon Nira"
	},
	"syndicate": {
		"SteelMeridianSyndicate": "Steel Meridian",
		"CephalonSudaSyndicate": "Cephalon Suda",
		"PerrinSyndicate": "The Perrin Sequence",
		"ArbitersSyndicate": "Arbiters of Hexis",
		"RedVeilSyndicate": "Red Veil",
		"NewLokaSyndicate": "New Loka",
		"VoxSyndicate": "Vox Solaris",
		"QuillsSyndicate": "The Quills",
		"VentKidsSyndicate": "Ventkids",
		"EventSyndicate": "Operational Supply",
		"NecraloidSyndicate": "Necraloid",
		"CetusSyndicate": "Ostron",
		"SolarisSyndicate": "Solaris United",
		"EntratiSyndicate": "Entrati",
		"ZarimanSyndicate": "The Holdfasts",
		"RadioLegionSyndicate": "Nightwave Series 1",
		"RadioLegion2Syndicate": "Nightwave Series 2",
		"RadioLegion3Syndicate": "Nightwave Series 3",
		"RadioLegionIntermissionSyndicate": "Nightwave Intermission",
		"RadioLegionIntermission2Syndicate": "Nightwave Intermission 2",
		"RadioLegionIntermission3Syndicate": "Nightwave Intermission 3",
		"RadioLegionIntermission4Syndicate": "Nightwave: Nora's Choice",
		"RadioLegionIntermission5Syndicate": "Nightwave: Nora's Mix Volume 1",
		"RadioLegionIntermission6Syndicate": "Nightwave: Nora's Mix Volume 2",
		"RadioLegionIntermission7Syndicate": "Nightwave: Nora's Mix Volume 3"
	},
	"sentientNode": {
		"505": "Ruse War Field",
		"510": "Gian Point",
		"550": "Nsu Grid",
		"551": "Ganalen's Grave",
		"552": "Rya",
		"553": "Flexa",
		"554": "H-2 Cloud",
		"555": "R-9 Cloud"
	},
	"voidStormTier": {
		"VoidT1": "Lith",
		"VoidT2": "Meso",
		"VoidT3": "Neo",
		"VoidT4": "Axi",
		"VoidT5": "Requiem",
		"VoidT6": "Omnia"
	},
	"baroNode": {
		"MercuryHUB": "Larunda Relay",
		"EarthHUB": "Strata Relay",
		"SaturnHUB": "Kronia Relay",
		"PlutoHUB": "Orcus Relay",
		"TennoConHUB2": "TennoCon Relay"
	},
	"region": {
		"1": "Mercury",
		"2": "Venus",
		"3": "Earth",
		"4": "Mars",
		"5": "Jupiter",
		"6": "Saturn",
		"7": "Uranus",
		"8": "Neptune",
		"9": "Pluto",
		"10": "Ceres",
		"11": "Eris",
		"12": "Sedna",
		"13": "Europa",
		"14": "Clan Dojo",
		"15": "Void",
		"16": "Phobos",
		"17": "Deimos",
		"18": "Lua",
		"19": "Kuva Fortress",
		"20": "Sanctuary Onslaught",
		"21": "Veil Proxima",
		"22": "Zariman Ten Zero",
		"23": "Höllvania",
		"24": "Tau System"
	},
	"missionType": {
		"MT_ASSASSINATION": "Assassination",
		"MT_EXTERMINATION": "Exterminate",
		"MT_SURVIVAL": "Survival",
		"MT_RESCUE": "Rescue",
		"MT_SABOTAGE": "Sabotage",
		"MT_CAPTURE": "Capture",
		"MT_COUNTER_INTEL": "Deception",
		"MT_INTEL": "Spy",
		"MT_DEFENSE": "Defense",
		"MT_MOBILE_DEFENSE": "Mobile Defense",
		"MT_PVP": "Conclave",
		"MT_MASTERY": "Mastery Rank Test",
		"MT_RECOVERY": "Recovery",
		"MT_TERRITORY": "Interception",
		"MT_RETRIEVAL": "Hijack",
		"MT_HIVE": "Hive Sabotage",
		"MT_SALVAGE": "Solar Rail Conflict",
		"MT_EXCAVATE": "Excavation",
		"MT_RAID": "Trial",
		"MT_PURIFY": "Infested Salvage",
		"MT_ARENA": "Rathuum",
		"MT_JUNCTION": "Junction",
		"MT_PURSUIT": "Pursuit",
		"MT_RACE": "Rush (Archwing)",
		"MT_ASSAULT": "Assault",
		"MT_EVACUATION": "Defection",
		"MT_LANDSCAPE": "Free Roam",
		"MT_ENDLESS_EXTERMINATION": "(Elite) Sanctuary Onslaught",
		"MT_ENDLESS_DUVIRI": "The Circuit",
		"MT_RAILJACK": "Empyrean",
		"MT_ARTIFACT": "Disruption",
		"MT_CORRUPTION": "Void Flood",
		"MT_VOID_CASCADE": "Void Cascade",
		"MT_ARMAGEDDON": "Void Armageddon",
		"MT_VAULTS": "Netracells",
		"MT_ALCHEMY": "Alchemy",
		"MT_ASCENSION": "Ascension",
		"MT_ENDLESS_CAPTURE": "Legacyte Harvest",
		"MT_OFFERING": "Shrine Defense",
		"MT_PVPVE": "Faceoff",
		"MT_DESCENT": "The Descendia",
		"MT_TAU_WAR": "The Perita Rebellion",
		"MT_PAINT_FLOOD": "Follie's Hunt"
	},
	"node": {
		"MercuryHUB": "Larunda Relay, Mercury",
		"VenusHUB": "Vesper Relay, Venus",
		"EarthHUB": "Strata Relay, Earth",
		"TradeHUB1": "Maroo's Bazaar, Mars",
		"SaturnHUB": "Kronia Relay, Saturn",
		"ErisHUB": "Kuiper Relay, Eris",
		"EuropaHUB": "Leonov Relay, Europa",
		"PlutoHUB": "Orcus Relay, Pluto",
		"ClanNode0": "Romula, Venus",
		"ClanNode1": "Malva, Venus",
		"ClanNode2": "Coba, Earth",
		"ClanNode3": "Tikal, Earth",
		"ClanNode4": "Sinai, Jupiter",
		"ClanNode5": "Cameria, Jupiter",
		"ClanNode6": "Larzac, Europa",
		"ClanNode7": "Cholistan, Europa",
		"ClanNode8": "Kadesh, Mars",
		"ClanNode9": "Wahiba, Mars",
		"ClanNode10": "Memphis, Phobos",
		"ClanNode11": "Zeugma, Phobos",
		"ClanNode12": "Caracol, Saturn",
		"ClanNode13": "Piscinas, Saturn",
		"ClanNode14": "Amarna, Sedna",
		"ClanNode15": "Sangeru, Sedna",
		"ClanNode16": "Ur, Uranus",
		"ClanNode17": "Assur, Uranus",
		"ClanNode18": "Akkad, Eris",
		"ClanNode19": "Zabala, Eris",
		"ClanNode20": "Yursa, Neptune",
		"ClanNode21": "Kelashin, Neptune",
		"ClanNode22": "Seimeni, Ceres",
		"ClanNode23": "Gabii, Ceres",
		"ClanNode24": "Sechura, Pluto",
		"ClanNode25": "Hieracon, Pluto",
		"SettlementNode1": "Roche, Phobos",
		"SettlementNode2": "Skyresh, Phobos",
		"SettlementNode3": "Stickney, Phobos",
		"SettlementNode10": "Kepler, Phobos",
		"SettlementNode11": "Gulliver, Phobos",
		"SettlementNode12": "Monolith, Phobos",
		"SettlementNode14": "Shklovsky, Phobos",
		"SettlementNode15": "Sharpless, Phobos",
		"SettlementNode20": "Iliad, Phobos",
		"SolNode1": "Galatea, Neptune",
		"SolNode2": "Aphrodite, Venus",
		"SolNode4": "Acheron, Pluto",
		"SolNode6": "Despina, Neptune",
		"SolNode9": "Rosalind, Uranus",
		"SolNode10": "Thebe, Jupiter",
		"SolNode11": "Tharsis, Mars",
		"SolNode12": "Elion, Mercury",
		"SolNode14": "Ultor, Mars",
		"SolNode15": "Pacific, Earth",
		"SolNode16": "Augustus, Mars",
		"SolNode17": "Proteus, Neptune",
		"SolNode18": "Rhea, Saturn",
		"SolNode19": "Enceladus, Saturn",
		"SolNode20": "Telesto, Saturn",
		"SolNode21": "Narcissus, Pluto",
		"SolNode22": "Tessera, Venus",
		"SolNode23": "Cytherean, Venus",
		"SolNode24": "Oro, Earth",
		"SolNode25": "Callisto, Jupiter",
		"SolNode26": "Lith, Earth",
		"SolNode27": "E Prime, Earth",
		"SolNode28": "Terminus, Mercury",
		"SolNode30": "Olympus, Mars",
		"SolNode31": "Anthe, Saturn",
		"SolNode32": "Tethys, Saturn",
		"SolNode33": "Ariel, Uranus",
		"SolNode34": "Sycorax, Uranus",
		"SolNode36": "Martialis, Mars",
		"SolNode38": "Minthe, Pluto",
		"SolNode39": "Everest, Earth",
		"SolNode41": "Arval, Mars",
		"SolNode42": "Helene, Saturn",
		"SolNode43": "Cerberus, Pluto",
		"SolNode45": "Ara, Mars",
		"SolNode46": "Spear, Mars",
		"SolNode48": "Regna, Pluto",
		"SolNode49": "Larissa, Neptune",
		"SolNode50": "Numa, Saturn",
		"SolNode51": "Hades, Pluto",
		"SolNode53": "Themisto, Jupiter",
		"SolNode56": "Cypress, Pluto",
		"SolNode57": "Sao, Neptune",
		"SolNode58": "Hellas, Mars",
		"SolNode59": "Eurasia, Earth",
		"SolNode60": "Caliban, Uranus",
		"SolNode61": "Ishtar, Venus",
		"SolNode62": "Neso, Neptune",
		"SolNode63": "Mantle, Earth",
		"SolNode64": "Umbriel, Uranus",
		"SolNode65": "Gradivus, Mars",
		"SolNode66": "Unda, Venus",
		"SolNode67": "Dione, Saturn",
		"SolNode68": "Vallis, Mars",
		"SolNode69": "Ophelia, Uranus",
		"SolNode70": "Cassini, Saturn",
		"SolNode72": "Outer Terminus, Pluto",
		"SolNode73": "Ananke, Jupiter",
		"SolNode74": "Carme, Jupiter",
		"SolNode75": "Cervantes, Earth",
		"SolNode76": "Hydra, Pluto",
		"SolNode78": "Triton, Neptune",
		"SolNode79": "Cambria, Earth",
		"SolNode81": "Palus, Pluto",
		"SolNode82": "Calypso, Saturn",
		"SolNode83": "Cressida, Uranus",
		"SolNode84": "Nereid, Neptune",
		"SolNode85": "Gaia, Earth",
		"SolNode87": "Ganymede, Jupiter",
		"SolNode88": "Adrastea, Jupiter",
		"SolNode89": "Mariana, Earth",
		"SolNode93": "Keeler, Saturn",
		"SolNode94": "Apollodorus, Mercury",
		"SolNode96": "Titan, Saturn",
		"SolNode97": "Amalthea, Jupiter",
		"SolNode98": "Desdemona, Uranus",
		"SolNode99": "War, Mars",
		"SolNode100": "Elara, Jupiter",
		"SolNode101": "Kiliken, Venus",
		"SolNode102": "Oceanum, Pluto",
		"SolNode103": "M Prime, Mercury",
		"SolNode104": "Fossa, Venus",
		"SolNode105": "Titania, Uranus",
		"SolNode106": "Alator, Mars",
		"SolNode107": "Venera, Venus",
		"SolNode108": "Tolstoj, Mercury",
		"SolNode109": "Linea, Venus",
		"SolNode113": "Ares, Mars",
		"SolNode114": "Puck, Uranus",
		"SolNode118": "Laomedeia, Neptune",
		"SolNode119": "Caloris, Mercury",
		"SolNode121": "Carpo, Jupiter",
		"SolNode122": "Stephano, Uranus",
		"SolNode123": "V Prime, Venus",
		"SolNode125": "Io, Jupiter",
		"SolNode126": "Metis, Jupiter",
		"SolNode127": "Psamathe, Neptune",
		"SolNode128": "E Gate, Venus",
		"SolNode129": "Orb Vallis, Venus",
		"SolNode130": "Lares, Mercury",
		"SolNode131": "Pallas, Ceres",
		"SolNode132": "Bode, Ceres",
		"SolNode135": "Thon, Ceres",
		"SolNode137": "Nuovo, Ceres",
		"SolNode138": "Ludi, Ceres",
		"SolNode139": "Lex, Ceres",
		"SolNode140": "Kiste, Ceres",
		"SolNode141": "Ker, Ceres",
		"SolNode144": "Exta, Ceres",
		"SolNode146": "Draco, Ceres",
		"SolNode147": "Cinxia, Ceres",
		"SolNode149": "Casta, Ceres",
		"SolNode153": "Brugia, Eris",
		"SolNode162": "Isos, Eris",
		"SolNode164": "Kala-azar, Eris",
		"SolNode166": "Nimus, Eris",
		"SolNode167": "Oestrus, Eris",
		"SolNode171": "Saxis, Eris",
		"SolNode172": "Xini, Eris",
		"SolNode173": "Solium, Eris",
		"SolNode175": "Naeglar, Eris",
		"SolNode177": "Kappa, Sedna",
		"SolNode181": "Adaro, Sedna",
		"SolNode183": "Vodyanoi, Sedna",
		"SolNode184": "Rusalka, Sedna",
		"SolNode185": "Berehynia, Sedna",
		"SolNode187": "Selkie, Sedna",
		"SolNode188": "Kelpie, Sedna",
		"SolNode189": "Naga, Sedna",
		"SolNode190": "Nakki, Sedna",
		"SolNode191": "Marid, Sedna",
		"SolNode193": "Merrow, Sedna",
		"SolNode195": "Hydron, Sedna",
		"SolNode196": "Charybdis, Sedna",
		"SolNode199": "Yam, Sedna",
		"SolNode203": "Abaddon, Europa",
		"SolNode204": "Armaros, Europa",
		"SolNode205": "Baal, Europa",
		"SolNode209": "Morax, Europa",
		"SolNode210": "Naamah, Europa",
		"SolNode211": "Ose, Europa",
		"SolNode212": "Paimon, Europa",
		"SolNode214": "Sorath, Europa",
		"SolNode215": "Valac, Europa",
		"SolNode216": "Valefor, Europa",
		"SolNode217": "Orias, Europa",
		"SolNode220": "Kokabiel, Europa",
		"SolNode223": "Boethius, Mercury",
		"SolNode224": "Odin, Mercury",
		"SolNode225": "Suisei, Mercury",
		"SolNode226": "Pantheon, Mercury",
		"SolNode228": "Plains of Eidolon, Earth",
		"SolNode229": "Cambion Drift, Deimos",
		"SolNode230": "Everview Arc, Zariman",
		"SolNode231": "Halako Perimeter, Zariman",
		"SolNode232": "Tuvul Commons, Zariman",
		"SolNode300": "Plato, Lua",
		"SolNode301": "Grimaldi, Lua",
		"SolNode302": "Tycho, Lua",
		"SolNode304": "Copernicus, Lua",
		"SolNode305": "Stöfler, Lua",
		"SolNode306": "Pavlov, Lua",
		"SolNode307": "Zeipel, Lua",
		"SolNode308": "Apollo, Lua",
		"SolNode309": "Yuvarium, Lua",
		"SolNode310": "Circulus, Lua",
		"SolNode400": "Teshub, Void",
		"SolNode401": "Hepit, Void",
		"SolNode402": "Taranis, Void",
		"SolNode403": "Tiwaz, Void",
		"SolNode404": "Stribog, Void",
		"SolNode405": "Ani, Void",
		"SolNode406": "Ukko, Void",
		"SolNode407": "Oxomoco, Void",
		"SolNode408": "Belenus, Void",
		"SolNode409": "Mot, Void",
		"SolNode410": "Aten, Void",
		"SolNode411": "Marduk, Void",
		"SolNode412": "Mithra, Void",
		"SolNode701": "Jordas Golem Assassinate",
		"SolNode705": "Mutalist Alad V Assassinate",
		"SolNode706": "Horend, Deimos",
		"SolNode707": "Hyf, Deimos",
		"SolNode708": "Phlegyas, Deimos",
		"SolNode709": "Dirus, Deimos",
		"SolNode710": "Formido, Deimos",
		"SolNode711": "Terrorem, Deimos",
		"SolNode712": "Magnacidium, Deimos",
		"SolNode713": "Exequias, Deimos",
		"SolNode715": "Effervo, Albrecht's Laboratories",
		"SolNode716": "Nex, Albrecht's Laboratories",
		"SolNode717": "Persto, Albrecht's Laboratories",
		"SolNode718": "Cambire, Albrecht's Laboratories",
		"SolNode740": "The Ropalolyst, Jupiter",
		"SolNode741": "Koro, Kuva Fortress",
		"SolNode742": "Nabuk, Kuva Fortress",
		"SolNode743": "Rotuma, Kuva Fortress",
		"SolNode744": "Taveuni, Kuva Fortress",
		"SolNode745": "Tamu, Kuva Fortress",
		"SolNode746": "Dakata, Kuva Fortress",
		"SolNode747": "Pago, Kuva Fortress",
		"SolNode748": "Garus, Kuva Fortress",
		"SolNode902": "Montes, Venus",
		"SolNode903": "Erpo, Earth",
		"SolNode904": "Syrtis, Mars",
		"SolNode905": "Galilea, Jupiter",
		"SolNode906": "Pandora, Saturn",
		"SolNode907": "Caelus, Uranus",
		"SolNode908": "Salacia, Neptune"
	},
	"sortieModifier": {
		"SORTIE_MODIFIER_LOW_ENERGY": "Energy Reduction",
		"SORTIE_MODIFIER_IMPACT": "Enemy Physical Enhancement: Impact",
		"SORTIE_MODIFIER_SLASH": "Enemy Physical Enhancement: Slash",
		"SORTIE_MODIFIER_PUNCTURE": "Enemy Physical Enhancement: Puncture",
		"SORTIE_MODIFIER_EXIMUS": "Eximus Stronghold",
		"SORTIE_MODIFIER_MAGNETIC": "Enemy Elemental Enhancement: Magnetic",
		"SORTIE_MODIFIER_CORROSIVE": "Enemy Elemental Enhancement: Corrosive",
		"SORTIE_MODIFIER_VIRAL": "Enemy Elemental Enhancement: Viral",
		"SORTIE_MODIFIER_ELECTRICITY": "Enemy Elemental Enhancement: Electricity",
		"SORTIE_MODIFIER_RADIATION": "Enemy Elemental Enhancement: Radiation",
		"SORTIE_MODIFIER_FIRE": "Enemy Elemental Enhancement: Heat",
		"SORTIE_MODIFIER_EXPLOSION": "Enemy Elemental Enhancement: Blast",
		"SORTIE_MODIFIER_FREEZE": "Enemy Elemental Enhancement: Cold",
		"SORTIE_MODIFIER_POISON": "Enemy Elemental Enhancement: Toxin",
		"SORTIE_MODIFIER_HAZARD_RADIATION": "Environmental Hazard: Radiation Pockets",
		"SORTIE_MODIFIER_HAZARD_MAGNETIC": "Environmental Hazard: Electromagnetic Anomalies",
		"SORTIE_MODIFIER_HAZARD_FOG": "Environmental Hazard: Dense Fog",
		"SORTIE_MODIFIER_HAZARD_FIRE": "Environmental Hazard: Fire",
		"SORTIE_MODIFIER_HAZARD_ICE": "Environmental Effect: Cryogenic Leakage",
		"SORTIE_MODIFIER_HAZARD_COLD": "Environmental Effect: Extreme Cold",
		"SORTIE_MODIFIER_ARMOR": "Augmented Enemy Armor",
		"SORTIE_MODIFIER_SHIELDS": "Enhanced Enemy Shields",
		"SORTIE_MODIFIER_SECONDARY_ONLY": "Weapon Restriction: Pistol Only",
		"SORTIE_MODIFIER_SHOTGUN_ONLY": "Weapon Restriction: Shotgun Only",
		"SORTIE_MODIFIER_SNIPER_ONLY": "Weapon Restriction: Sniper Only",
		"SORTIE_MODIFIER_RIFLE_ONLY": "Weapon Restriction: Assault Rifle Only",
		"SORTIE_MODIFIER_MELEE_ONLY": "Weapon Restriction: Melee Only",
		"SORTIE_MODIFIER_BOW_ONLY": "Weapon Restriction: Bow Only"
	},
	"language": {
		"de": "German",
		"en": "English",
		"es": "Spanish",
		"fr": "French",
		"it": "Italian",
		"ja": "Japanese",
		"ko": "Korean",
		"pl": "Polish",
		"pt": "Portuguese (Brazil)",
		"ru": "Russian",
		"tc": "Chinese (Traditional)",
		"th": "Thai",
		"tr": "Turkish",
		"uk": "Ukrainian",
		"zh": "Chinese (Simplified)"
	},
	"conclaveMode": {
		"PVPMODE_ALL": "Any Mode",
		"PVPMODE_CAPTURETHEFLAG": "Cephalon Capture",
		"PVPMODE_DEATHMATCH": "Annihilation",
		"PVPMODE_NONE": "None",
		"PVPMODE_SPEEDBALL": "Lunaro",
		"PVPMODE_TEAMDEATHMATCH": "Team Annihilation"
	},
	"faction": {
		"FC_CORPUS": "Corpus",
		"FC_CORRUPTED": "Corrupted",
		"FC_GRINEER": "Grineer",
		"FC_INFESTATION": "Infestation",
		"FC_MITW": "The Murmur",
		"FC_SCALDRA": "Scaldra",
		"FC_SENTIENT": "Sentient",
		"FC_TECHROT": "Techrot"
	},
	"boss": {
		"SORTIE_BOSS_ALAD": "Alad V",
		"SORTIE_BOSS_AMAR": "Archon Amar",
		"SORTIE_BOSS_AMBULAS": "Ambulas",
		"SORTIE_BOSS_BOREAL": "Archon Boreal",
		"SORTIE_BOSS_CORRUPTED_VOR": "Corrupted Vor",
		"SORTIE_BOSS_NEF": "Nef Anyo",
		"SORTIE_BOSS_HEK": "Councilor Vay Hek",
		"SORTIE_BOSS_HYENA": "Hyena Pack",
		"SORTIE_BOSS_INFALAD": "Mutalist Alad V",
		"SORTIE_BOSS_JACKAL": "Jackal",
		"SORTIE_BOSS_KELA": "Kela De Thaym",
		"SORTIE_BOSS_KRIL": "Lieutenant Lech Kril",
		"SORTIE_BOSS_LEPHANTIS": "Lephantis",
		"SORTIE_BOSS_NIRA": "Archon Nira",
		"SORTIE_BOSS_PHORID": "Phorid",
		"SORTIE_BOSS_RAPTOR": "Raptors",
		"SORTIE_BOSS_RUK": "General Sargas Ruk",
		"SORTIE_BOSS_TYL": "Tyl Regor",
		"SORTIE_BOSS_VOR": "Captain Vor"
	},
	"weaponRestriction": {
		"/Lotus/Weapons/Tenno/Bow/LotusBow": "Bows (Primary)",
		"/Lotus/Weapons/Tenno/Melee/LotusMelee": "Melee",
		"/Lotus/Weapons/Tenno/Pistol/LotusPistol": "Pistols (Secondary)",
		"/Lotus/Weapons/Tenno/Rifle/LotusRifle": "Rifles (Primary)",
		"/Lotus/Weapons/Tenno/Shotgun/LotusShotgun": "Shotguns (Primary)"
	},
	"difficulty": {
		"CD_NORMAL": "normal",
		"CD_HARD": "Elite Archimedea",
		"EXC_NORMAL": "normal",
		"EXC_HARD": "Steel Path"
	}
} as const;

export type WorldStateMapping = keyof typeof worldStateMappings;

export function worldStateLabel(category: WorldStateMapping, key: string, fallback = ''): string {
	const labels: Readonly<Record<string, string>> = worldStateMappings[category];
	if (Object.hasOwn(labels, key)) return labels[key];
	// Archimedea uses full localization paths while the document lists their suffixes.
	const segment = key.split('/').pop() ?? key;
	const prefixes: Partial<Record<WorldStateMapping, string>> = {
		temporalDeviation: 'MissionVariant_HexConquest_',
		deepDeviation: 'MissionVariant_LabConquest_',
		archimedeaRisk: 'Condition_',
		archimedeaModifier: 'PersonalMod_',
	};
	const prefix = prefixes[category];
	const shortKey = prefix && segment.startsWith(prefix) ? segment.slice(prefix.length) : segment;
	return Object.hasOwn(labels, shortKey) ? labels[shortKey] : fallback;
}
