// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Debug image sent to the dashboard for visual inspection.
 */
export type OcrDebugImagePayload = { png_bytes: Array<number>, width: number, height: number, upscale_amount: number, };
