// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OcrPipelineConfig = { upscale_factor: number, min_pixel_density: number, dice_sorensen_threshold: number, page_seg_mode: number, emit_debug_overlay: boolean, };
