// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OcrWord } from "./OcrWord";

/**
 * Payload emitted to the frontend with OCR results.
 */
export type OcrPayload = { words: Array<OcrWord>, show_ocr_bounding_boxes: boolean, };
