// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selectable theme entry shown in the settings UI.
 */
export type OcrThemeOption = { name: string, rgb: [number, number, number], };
