// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw OCR text sent to the dashboard (when enabled).
 */
export type OcrTextPayload = { text: string, };
