// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModType } from "./ModType";

/**
 * A single recognized word/block with optional dictionary match metadata.
 */
export type OcrWord = { text: string, x: number, y: number, width: number, height: number, confidence: number, slug: string | null, mapping_confidence: number | null, market_median: number | null, market_median_from_current_offers: boolean | null, relic_price_is_fallback: boolean | null, ducats: bigint | null, vaulted: boolean | null, is_custom: boolean | null, is_relic: boolean | null, subtype: string | null, trades_24h: number | null, moving_avg: number | null, mod_type: ModType | null, };
